name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # 直接拉到最高版本

      - name: Install Tools
        run: |
          npm install -g @capacitor/cli @capacitor/core
          npm install --force

      - name: Build Android Project
        run: |
          # 确保 www 文件夹存在，没有就建一个空的防止报错
          mkdir -p www
          # 彻底清理并重新生成安卓壳子
          rm -rf android
          npx cap add android
          npx cap sync

      - name: Build APK with Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-launcher-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
